### ISSUE TITLE
개발서버의 API  장비등록 GET 을 송부 했으나 아무 응답이 없음

### ISSUE THREAD

**Issue by seokgoo** [rchemist/enfinity-docs#1]
Tenant : sgoh63
serial : 2024030001

의 정보로 보냈으나 응답이 없음.
왔는지 확인 바람.

**Comment by kimhyunri1** [comment]
안녕하세요.

1. 현재 등록되지 않은 장비 정보로 인해 데이터가 나오지 않았습니다.
에너지 관리 > 발전소 > 상세 정보 > 신규 데이터 입력 후 장비를 등록하시고,  enfinity-rems 연동 가이드 매뉴얼의 4.2. 장비 정보 등록을 참고하시기 바랍니다.


2.  응답은 성공 또는 실패로 나오며, 기입하신 테넌트 아이디와 시리얼 아이디로 테스트를 진행한 결과, 응답이 성공적으로 반환되었음을 확인했습니다. 
{
    "error": {
        "error": true,
        "status": 404,
        "errorType": "NOT_FOUND",
        "message": "Not Found",
        "fieldError": {}
    }
}

하지만 데이터가 등록되지 않아서 응답이 실패로 나오고 있습니다.


3. 리퀘스트 정보를 기입해주셔야 올바른 답변을 드릴 수 있으니 정확히 기재 부탁드립니다.
