### ISSUE TITLE
업체정보관리 입력 오류

### ISSUE THREAD

**Issue by seokgoo** [rchemist/enfinity-docs#2]
업체 정보관리에서 저장을 하면 아래 오류가 발생

JSON parse error: Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`)

**Comment by kimhyunri1** [comment]
현재 업체 정보를 입력하면 정상적으로 저장이 되고 있습니다. 

업체 정보 입력 시 필수 입력 값으로 무엇을 입력하셨는지 기재해주시면  정확한 확인이 가능할 것 같습니다.

**Comment by seokgoo** [comment]
위와 같이 입력 했습니다.
비번은 저번과 같습니다.



-----Original Message-----

**Comment by kimhyunri1** [comment]
1. 추가 정보나 첨부 파일이 없어서 확인이 어렵습니다. 입력하신 내용을 캡쳐본으로 첨부해 주시거나 정확한 값을 기재해 주시길 부탁드립니다.
2. 비밀번호는 혹시  10184Goh!!&  이게 맞는지 확인 부탁드립니다.

**Comment by seokgoo** [comment]
아래 참조 부탁 드립니다.

-----Original Message-----

**Comment by kimhyunri1** [comment]
메일로 보내주셨을까요? 캡쳐본이 첨부되지 않았는데, 이 부분 다시 확인 부탁드립니다!
